from __future__ import annotations

COMPARE_SELECTION_QUERY_KEY = "compare"
COMPARE_SELECTION_MAX_RESORTS = 4
COMPARE_SELECTION_BOOTSTRAP = {
    "queryKey": COMPARE_SELECTION_QUERY_KEY,
    "maxResorts": COMPARE_SELECTION_MAX_RESORTS,
}
